# Generated by Django 5.2.8 on 2025-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imageslides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slid_image",
                    models.ImageField(blank=True, upload_to="./slide_images/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="./blog_images/"),
        ),
    ]
