# Generated by Django 5.2.8 on 2025-12-01 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_imageslides_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageslides",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageslides",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="imageslides",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
