# Generated by Django 5.2.8 on 2025-12-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_imageslides_count_imageslides_published_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageslides",
            old_name="slid_image",
            new_name="slide_image",
        ),
    ]
