# Generated by Django 5.2.8 on 2025-12-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_slid_image_imageslides_slide_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=10000, unique=True),
        ),
    ]
