# Generated by Django 5.2.8 on 2025-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="subtitle",
            field=models.CharField(max_length=300),
        ),
    ]
