# Generated by Django 5.2.8 on 2025-12-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_slug_alter_post_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
